# Generated by Django 2.1.7 on 2019-03-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=11, verbose_name='手机号')),
                ('upwd', models.CharField(max_length=20, verbose_name='密码')),
                ('uwei', models.CharField(max_length=20, verbose_name='微信')),
                ('uqq', models.CharField(max_length=15, verbose_name='QQ')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('uaddres', models.CharField(max_length=50, verbose_name='收货地址')),
                ('uchoice', models.CharField(default='纸质发票', max_length=10, verbose_name='发票类型')),
                ('isActive', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, verbose_name='单位名称')),
                ('upwd', models.CharField(max_length=20, verbose_name='单位税号')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
    ]
