# Generated by Django 2.1.7 on 2019-03-31 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190331_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='custom',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.user'),
        ),
    ]
