# Generated by Django 2.1.7 on 2019-03-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190331_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='user',
            field=models.ManyToManyField(to='index.user'),
        ),
    ]
