# Generated by Django 2.1.7 on 2019-03-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20190331_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': '单位信息', 'verbose_name_plural': '单位信息'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='userd',
        ),
        migrations.AddField(
            model_name='user',
            name='unitd',
            field=models.ManyToManyField(to='index.unit'),
        ),
    ]
