# Generated by Django 2.1.7 on 2019-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20190331_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unitd',
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ManyToManyField(to='index.customer'),
        ),
    ]
