# Generated by Django 2.1.7 on 2019-04-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20190402_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单总表', 'verbose_name_plural': '订单总表'},
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='customer',
        ),
    ]
