# Generated by Django 2.1.7 on 2019-04-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20190406_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='uname',
            field=models.CharField(max_length=50, verbose_name='单位名称'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='upwd',
            field=models.CharField(max_length=50, verbose_name='单位税号'),
        ),
    ]
