# Generated by Django 2.1.7 on 2019-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20190406_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alldata',
            options={'ordering': ['unit'], 'verbose_name': '总表', 'verbose_name_plural': '总表'},
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ManyToManyField(to='index.customer'),
        ),
    ]
