# Generated by Django 2.1.7 on 2019-04-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20190420_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='unit',
            field=models.ManyToManyField(to='index.unit'),
        ),
    ]
